### ISSUE TITLE
Mirror NSIS sources and plugins

### ISSUE THREAD

**Issue by jaimergp** [conda-incubator/installer#5]
For provenance and reproducibility, we shouldn't rely on ephemeral wikis :D 

[I added a mirror on my account](https://github.com/jaimergp/nsis-mirror), happy to transfer over to this org (or `conda`).

xref https://github.com/conda-forge/nsis-feedstock/issues/23

**Comment by isuruf** [comment]
Thanks for doing this. Shall we transfer it to `conda-incubator` org? cc @jezdez

**Comment by jezdez** [comment]
@isuruf Good idea! I think adding the mirror to the installer team would be pretty simple to do

**Comment by jaimergp** [comment]
Aaand done! https://github.com/conda/nsis-mirror

Thanks @jezdez! I'll put a PR on conda-forge's feedstock now.
